version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: flight_reservations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0012345
    ports:
      - "5433:5433"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672" # Interfaz de gestión

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flight_reservations
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0012345
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
